### ISSUE TITLE
Upgraded to Kodi Leia 18.6 and UsaTvGo stopped working

### ISSUE THREAD

**Issue by anthob1** [Tempest0580/tempest#38]
Hello (big fan of your work),
I recently Upgraded to Kodi Leia 18.6 and UsaTvGo stopped working. Not sure if this helps, but tried some TVTap channels, and Achronai channels and some other channel sections in your app, and all seemed to be be working (mostly) so it seems only UsaTvGo is affected (???).

And I just have to tell you - on an unrelated note - that Tempest an TempTV are by far the best apps I've ever used. Better than Exodus, Covenant, etc. etc. and what makes them so good is your costant attention to upkeep. In fact- You've Spoiled Me! Ever since Tempest, and then TempTV, I no longer keep other similar apps installed 'just incase.' Your dilligent work has allowed me to become a true cord cutter and I wanted to thank you for that. And it really makes me mad to see the closed thread about others swiping your scrapers without permission, and with no recognition (but I suppose those types will always be among us {sigh}).     SO, if there is any way thay I could help, please let me know. Not a coder, but would gladly donate financially, even a monthly, if that might help. Yours is simply the best. Hands down. And I would hate to see you get discouraged because of the laziness and lack of respect of certain so and so's. ...sorry this went so long but just wanted to mention that.

**Comment by Tempest0580** [comment]
Thanks that's good to hear. 
As far as ustvgo.  The site has been going up and down. From what I have read the servers have been overloaded with so many people off work right now. Not sure if they are changing things to break my code or what. But once the servers lvl out if I need/can fix it I will. 
Thanks

**Comment by ap0192837465** [comment]
Hello, I'm also a big fan of your work.

Thank you very much for what you have been doing during this time. Before I got to know this project, I used a lot of addons and today I only have TempTv and Tempest in my box. I'm using Kodi Leia 18.6 and since Tuesday (03/31) at 3:00 pm until now, when you select the UsaTv Go list, I can't open any channels, but if I use 123Tvnow I can open the channels normally, but this tab is not as good as UsaTv Go. I noticed that on Tuesday (03/31) around 4:00 pm the UsaTv Go site went offline and came back the next day (04/01) at 8:00 am, since then I am no longer able to access UsaTv Go. I participate in a group of Kodi addons and other people are also having the same problem related to me and my friend from above. Just to let you know, I'm not sure if it was the changes from Kodi 18.5 to 18.6 that were affected or if there was really any change on the website that needs to change the TempTv and Tempest addons to continue working normally. After all, the site was down for a long time and I believe there was some change.

Thank you very much for everything friend, keep doing a great job.

Sincerely.

**Comment by ap0192837465** [comment]
Hello, I'm also a big fan of your work.

Thank you very much for what you have been doing during this time. Before I got to know this project, I used a lot of addons and today I only have TempTv and Tempest in my box. I'm using Kodi Leia 18.6 and since Tuesday (03/31) at 3:00 pm until now, when you select the UsaTv Go list, I can't open any channels, but if I use 123Tvnow I can open the channels normally, but this tab is not as good as UsaTv Go. I noticed that on Tuesday (03/31) around 4:00 pm the UsaTv Go site went offline and came back the next day (04/01) at 8:00 am, since then I am no longer able to access UsaTv Go. I participate in a group of Kodi addons and other people are also having the same problem related to me and my friend from above. Just to let you know, I'm not sure if it was the changes from Kodi 18.5 to 18.6 that were affected (which I find very difficult) or if there was really any change on the website that needs to change the TempTv and Tempest addons to continue working normally. I am not able to access during these last two days, Now for example I can not open the list of UsaTv Go and the site is online. After all, the site was down for a long time and I believe there was some change.

Ps: I already installed Kodi again and tried to install the repository and continue the same way

Thank you very much for everything friend, keep doing a great job.

Sincerely.

**Comment by Tempest0580** [comment]
As of today ustvgo has changed and added more security.  I'm in the process off writing a fix. As soon as I get it worked out I'll push a update. 
Thanks

**Comment by Tempest0580** [comment]
Pushed a update, Its a crude fix for now. May have to click the channels more than once.
Working on a better fix.
Thanks

**Comment by ap0192837465** [comment]
Thanks for trying to fix it, I received your update recently to click on channels more than once. For now UsaTv Go is not working even though trying to click several times. At the moment, 123Tvnow help me out. Thanks again, for your work.

**Comment by Tempest0580** [comment]
Pushed a update hopefully it will stay working for a while. Should come through shortly. 
Thanks

**Comment by meNick** [comment]
Well, as of right now both Tempest and TempTv are going up and down on channels (ustvgo & streamLive, FoxNew,) very unstable.

Just saying (not complaining). Just FYI.

**Comment by ap0192837465** [comment]
Good evening, coming back here to say you, thank you for the update work done in the last few days. Thank you very much for making UsaTv Go work again.

I was chatting with a friend 5 days ago, and he commented on an iptv pluugin called ``Swift Stream live TV`` (I will attach the plugin here). I would like to know if it is possible to add one more line of IPTV together with the add-on `TempTv` and` Tempest`. Thanks

[script.module.7of9-swiftstreamz.zip](https://github.com/Tempest0580/tempest/files/4453623/script.module.7of9-swiftstreamz.zip)

PS .: This addon, has IPTV from several countries, you could leave only the USA.

**Comment by ap0192837465** [comment]
Well, I didn't know that @meNick - But, when TempTV was having a problem this past week, I used these Swift Stream live TV addons. It is in the Diamonte repository. When I used it, the USA list was working perfectly (same as TempTV). And in this period I had no problem even there was no buffering. So I asked @Tempest0580  if it was possible to add to the list of TempTV and Tempest.

**Comment by ap0192837465** [comment]
Well, I didn't know that @meNick - but, when TempTV was having a problem this past week, I used these Swift Stream live TV addons. It is in the Diamonte repository. When I used it, the USA list was working perfectly (same as TempTV, same channels, but with links directly from the apk). And in this period I had no problem even there no buffering. But today I am using TempTV again because its clean, it is irreplaceable. So I asked @Tempest0580 if it was possible to add to the list of TempTV and Tempest.

**Comment by meNick** [comment]
@ap0192837465 - Hi, I tried Swift Stream and same repo you used just last night as a test and it did not work for me. It used to work but stopped months ago.

But I think it might be because I used Kodi 17.6 (not 18), so maybe that dev made a change to his plugin. So I don't know if Kodi version is making a difference.

Of course, I think you should ask the Dev of TempTv/Tempest anything you want -- I was only contributing my experience. I hope I did not muddy up the waters.

Stay safe :)

**Comment by ap0192837465** [comment]
@meNick Thank you bro. No problem, don't worry. I installed it directly from the repository and my Kodi is updated 18.6 Read, it could be that. But, it works well here. Let's wait for our friend's reply @Tempest0580 . Thank you guys, you guys are awesome.

**Comment by Tempest0580** [comment]
Sorry I haven't replied.  My computer messed up been trying to fix it. I'll look into adding swift to my addons. Looking into some more live streams to add also.
Thanks

**Comment by ap0192837465** [comment]
I hope it is nothing serious and you can get it again soon. Thank you for answering the request @Tempest0580 . Let's do TempTV and Tempest at the top #1. I think the addon is missing a CBS Sports Network channel. 😉

**Comment by ap0192837465** [comment]
Hello, I use Tv Guide on my Kodi and noticed that the 123tvnow link has not been working since 04/13 inside TempTv. When you have time @Tempest0580 can you check it out please? Thank you

**Comment by meNick** [comment]
I use Kodi 17.6, when I click on 123tvnow on TenpTv addon today (4/15/20) I get a screen showing all available channels.

However, when I chick on any of the channels then nothing happens. No error, no video, no nothing.



Hope that helps you.


---- On Wed, 15 Apr 2020 11:50:56 -0500 ap0192837465 <notifications@github.com> wrote ----




Hello, I use Tv Guide on my Kodi and noticed that the 123tvnow link has not been working since 04/13 inside TempTv. When you have time https://github.com/Tempest0580 can you check it out please? Thank you

**Comment by Tempest0580** [comment]
I'll look into it.

**Comment by Tempest0580** [comment]
Pushed a update. Added a new live tv source(Testing). Removed arconaitv until I can fix it or find a new source. I'll work on 123tvnow next.
Thanks

**Comment by meNick** [comment]
@Tempest0580   Installed 5.0.51 and all seems to work well (using Kodi 17.6) on both Windows & Android.
That includes the new ZyneTv channel.

So go ahead and take a break... but not for too long now... oh and by the way... Thanks!"

**Comment by ap0192837465** [comment]
Good morning guys, @Tempest0580 my Kodi version 18.6 Leia, I got the update now in the morning (04/18) TempTv version: 2.0.62 video plugin. UsaTv Go stopped work the channels (Last nigth, it was working normally) 123Tvnow, no channels working yet and Zyne Tv does not work any channels except the first two 5 Star and 5 USA. Thank you.

**Comment by ap0192837465** [comment]
Good morning guys, @Tempest0580 my Kodi version 18.6 Leia, I got the update now in the morning (04/18) TempTv version: 2.0.62 video plugin. UsaTv Go stopped work the channels (Last nigth, it was working normally) 123Tvnow, no channels working yet and Zyne Tv does not work any channels except the first two 5 Star and 5 USA. The same goes for the Tempest version 5.0.51. Thank you.

**Comment by Tempest0580** [comment]
Unfortunately both sites are screwed at the moment.  Looks like both sites run off ustvgo. I'm working on another site now. Just have to get my code right.

**Comment by meNick** [comment]
@Tempest0580  Glad to hear you keep working at both plugins. It must be nuts when you spend the time and they last just a day or two. I know there are a lot of us that use live tv all the time.

And there is no plugin(s) better than yours, so keep at it. And thank you.
