### ISSUE TITLE
Metalliq 4qed player not working

### ISSUE THREAD

**Issue by Roywirges** [Tempest0580/tempest#5]
Hello,

I love this addon and truly appreciate the time you spend keeping it updated!  I use Metalliq 4qed in my personal builds but have noticed that the tempest player does not work when selected from the list of available addons.

Any chance of including a working metalliq player in a new update?

Sincerely,
Roy

**Comment by Tempest0580** [comment]
I'll take a look into that for you.

**Comment by Roywirges** [comment]
Thank you for your quick response! I really appreciate you looking into it.

Regards
Roy

**Comment by jewbmx** [comment]
Dont know if this issue is needing closed but your can probably do the player file needed for this by using a file like this one  https://github.com/a4k-openproject/json.openplayers/blob/master/direct.scrubsv2.json

I dont use none of that shit but i think you could just swap the scrubs names to tempest and be all good or post there and get em to make one lol.

**Comment by Tempest0580** [comment]
You might be able to get them to make it for you so they can puss it to there version.  I'll be honest I haven't had much time. Trying to keep tempest updated and I have a new project a live TV addon I'm working on that's taking alot of my time.

**Comment by Roywirges** [comment]
I wound up making my own a while back and it has worked great so far. Thank
you for the response though.

**Comment by Tempest0580** [comment]
No problem.  I'll keep this open for now. If you cant get them to add my addon I'll try to find some time to look in to it more.
